// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PalletsApiCore.Models;

[Table("cenker_prod_x_pallet", Schema = "web")]
public partial class cenker_prod_x_pallet
{
    [Key]
    public Guid id { get; set; }

    public Guid pallet_id { get; set; }

    public Guid producto_id { get; set; }

    public bool? activo { get; set; }

    [Column(TypeName = "character varying")]
    public string fecha_alta { get; set; }

    [Column(TypeName = "character varying")]
    public string fecha_modificacion { get; set; }

    [Required]
    [Column(TypeName = "character varying")]
    public string serie { get; set; }
}