// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PalletsApiCore.Models;

public partial class ESCORIALContext : DbContext
{
    public ESCORIALContext()
    {
    }

    public ESCORIALContext(DbContextOptions<ESCORIALContext> options)
        : base(options)
    {
    }

    public virtual DbSet<cenker_pallets> cenker_pallets { get; set; }

    public virtual DbSet<cenker_prod_x_pallet> cenker_prod_x_pallet { get; set; }

    public virtual DbSet<etiquetas_maestro_cocinas> etiquetas_maestro_cocinas { get; set; }

    public virtual DbSet<etiquetas_maestro_termotanques> etiquetas_maestro_termotanques { get; set; }

    public virtual DbSet<producto> producto { get; set; }

    public virtual DbSet<vp_etiquetas> vp_etiquetas { get; set; }

    public virtual DbSet<ud_empleado> ud_empleado { get; set; }

    public virtual DbSet<empleado> empleado { get; set; }

    public virtual DbSet<v_persona> v_persona { get; set; }

    public virtual DbSet<cenker_pallets_auditoria> cenker_pallets_auditoria { get; set; }

    public virtual DbSet<aux_controlcalidad> aux_controlcalidad { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) { }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("fuzzystrmatch")
            .HasPostgresExtension("hstore")
            .HasPostgresExtension("ltree")
            .HasPostgresExtension("pg_stat_statements")
            .HasPostgresExtension("pgstattuple")
            .HasPostgresExtension("unaccent");

        modelBuilder.Entity<cenker_pallets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("cenker_pallets_pkey");

            entity.Property(e => e.id).ValueGeneratedNever();
        });

        modelBuilder.Entity<cenker_prod_x_pallet>(entity =>
        {
            entity.HasKey(e => e.id).HasName("cenker_prod_x_pallet_pkey");

            entity.Property(e => e.id).ValueGeneratedNever();
        });

        modelBuilder.Entity<etiquetas_maestro_cocinas>(entity =>
        {
            entity.HasKey(e => e.numero).HasName("pk_etiquetas_maestro_cocinas_numero");

            entity.Property(e => e.numero).ValueGeneratedNever();
            entity.Property(e => e.ingreso_stock).HasDefaultValue(false);
            entity.Property(e => e.paso_lector).HasDefaultValue(false);
            entity.Property(e => e.paso_lector_manual).HasDefaultValue(false);
            entity.Property(e => e.reprocesado).HasDefaultValue(false);
            entity.Property(e => e.transfer_disabled).HasDefaultValue(false);
        });

        modelBuilder.Entity<etiquetas_maestro_termotanques>(entity =>
        {
            entity.HasKey(e => e.numero).HasName("pk_etiquetas_maestro_termotanques_numero");

            entity.Property(e => e.numero).ValueGeneratedNever();
            entity.Property(e => e.ingreso_stock).HasDefaultValue(false);
            entity.Property(e => e.paso_lector).HasDefaultValue(false);
            entity.Property(e => e.paso_lector_manual).HasDefaultValue(false);
            entity.Property(e => e.reprocesado).HasDefaultValue(false);
            entity.Property(e => e.transfer_disabled).HasDefaultValue(false);
        });

        modelBuilder.Entity<ud_empleado>(entity =>
        {
            entity.HasKey(e => e.id).HasName("ud_empleado_pkey");
            entity.Property(e => e.id).ValueGeneratedNever();
        });

        modelBuilder.Entity<cenker_pallets_auditoria>(entity =>
        {
            entity.HasKey(e => e.id).HasName("cenker_pallets_auditoria_pkey");
            entity.Property(e => e.id).ValueGeneratedNever();
        });

        modelBuilder.Entity<empleado>(entity =>
        {
            entity.HasKey(e => e.id).HasName("empleado_pkey");
            entity.Property(e => e.id).ValueGeneratedNever();
        });

        modelBuilder.Entity<aux_controlcalidad>(entity =>
        {
            entity.Property(e => e.etiqueta).ValueGeneratedNever();
        });

        modelBuilder.Entity<producto>(entity =>
        {
            entity.HasKey(e => e.id).HasName("producto_pkey");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.activestatus).HasDefaultValue(0);
            entity.Property(e => e.alto).HasDefaultValueSql("0.0");
            entity.Property(e => e.ancho).HasDefaultValueSql("0.0");
            entity.Property(e => e.bienuso).HasDefaultValue(false);
            entity.Property(e => e.calculoexinolineal).HasDefaultValue(false);
            entity.Property(e => e.cantidad).HasDefaultValue(0);
            entity.Property(e => e.concatcodprod).HasDefaultValue(false);
            entity.Property(e => e.creacioncodalt).HasDefaultValue(false);
            entity.Property(e => e.esmultiplodebultos).HasDefaultValue(false);
            entity.Property(e => e.espesor).HasDefaultValueSql("0.0");
            entity.Property(e => e.existenciaobligatoria).HasDefaultValue(false);
            entity.Property(e => e.existenciaobligatorianl).HasDefaultValue(false);
            entity.Property(e => e.explotapropiedades).HasDefaultValue(false);
            entity.Property(e => e.explotaserieeninventario).HasDefaultValue(false);
            entity.Property(e => e.kit).HasDefaultValue(false);
            entity.Property(e => e.montoproducto).HasDefaultValueSql("0.0");
            entity.Property(e => e.montototal).HasDefaultValueSql("0.0");
            entity.Property(e => e.peso).HasDefaultValueSql("0.0");
            entity.Property(e => e.porcentajecategoria).HasDefaultValueSql("0.0");
            entity.Property(e => e.porcentajereposicion).HasDefaultValueSql("0.0");
            entity.Property(e => e.puntopedido).HasDefaultValueSql("0.0");
            entity.Property(e => e.stockmaximo).HasDefaultValueSql("0.0");
            entity.Property(e => e.stockminimo).HasDefaultValueSql("0.0");
            entity.Property(e => e.stockoptimo).HasDefaultValueSql("0.0");
            entity.Property(e => e.stockseguridad).HasDefaultValueSql("0.0");
            entity.Property(e => e.unidadesporbulto).HasDefaultValueSql("0.0");
            entity.Property(e => e.unidminimcomer).HasDefaultValueSql("0.0");
            entity.Property(e => e.utilcnltotalitem).HasDefaultValue(false);
            entity.Property(e => e.utilizacantidadnolineal).HasDefaultValue(false);
            entity.Property(e => e.utilizaseriedetallada).HasDefaultValue(false);
            entity.Property(e => e.volumen).HasDefaultValueSql("0.0");
        });

        modelBuilder.Entity<vp_etiquetas>(entity =>
        {
            entity.ToView("vp_etiquetas");
        });

        modelBuilder.Entity<v_persona>(entity =>
        {
            entity.ToView("v_persona");
        });

        modelBuilder.HasSequence("aux_suceso_inc_seq");
        modelBuilder.HasSequence("hibernate_sequence", "web");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}