// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PalletsApiCore.Models;

[Table("etiquetas_maestro_termotanques", Schema = "web")]
[Index("estado", Name = "idx_etiquetas_maestro_termotanques_estado")]
[Index("fecha", Name = "idx_etiquetas_maestro_termotanques_fecha")]
[Index("idproducto", Name = "idx_etiquetas_maestro_termotanques_idproducto")]
[Index("numero", Name = "idx_etiquetas_maestro_termotanques_numero")]
public partial class etiquetas_maestro_termotanques
{
    [Key]
    public int numero { get; set; }

    [StringLength(50)]
    public string modelo { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? fecha { get; set; }

    [StringLength(50)]
    public string idproducto { get; set; }

    [StringLength(50)]
    public string usuario { get; set; }

    public int? estado { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? fecha_eliminacion { get; set; }

    [StringLength(50)]
    public string eliminadapor { get; set; }

    [StringLength(150)]
    public string motivo { get; set; }

    public bool? transfer_disabled { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? ultima_fecha_paso_lector { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? fecha_ingreso_stock { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? fecha_paso_lector { get; set; }

    public bool? ingreso_stock { get; set; }

    public bool? paso_lector_manual { get; set; }

    [StringLength(255)]
    public string usuario_ingreso_lector { get; set; }

    public bool? paso_lector { get; set; }

    public bool? reprocesado { get; set; }
}