// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
# nullable disable

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PalletsApiCore.Models
{
    [Table("ud_empleado", Schema = "public")]
    public class ud_empleado
    {
        [Key]
        [Column("id")]
        public Guid id { get; set; }
        [Column("usuario_sistema", TypeName = "character varying")]
        [StringLength(40)]
        public string usuario_sistema { get; set; }
        [Column("password", TypeName = "character varying")]
        [StringLength(20)]
        public string password { get; set; }
    }
}
