// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PalletsApiCore.Models;

[Keyless]
public partial class vp_etiquetas
{
    public int? numero { get; set; }

    public Guid? producto_id { get; set; }

    public string producto_c { get; set; }

    [StringLength(50)]
    public string producto_n { get; set; }

    public string tipo { get; set; }

    public bool? ingreso_stock { get; set; }

    [Column("fecha_paso_lector", TypeName = "timestamp without time zone")]
    public DateTime? fecha_paso_lector { get; set; }
}